version: '3'
services:
  local-linguist-server:
    build: ..
    ports:
      - "3000:3000"
    depends_on:
      - local-linguist-db
  local-linguist-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
  local-linguist-test:
    build: ..
    depends_on:
      - local-linguist-db
    command: rake
