version: '3'
services:
  local-linguist-server:
    build: ..
    ports:
      - "3000:3000"
    depends_on:
      - db_init
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
  db_init:
    build: ..
    depends_on:
      - db
    command: ./prep_db.sh
  test:
    build: ..
    depends_on:
      - db_init
    command: rake
