require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InterviewsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Interview. As you add validations to Interview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InterviewsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all interviews as @interviews" do
      interview = Interview.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:interviews)).to eq([interview])
    end
  end

  describe "GET #show" do
    it "assigns the requested interview as @interview" do
      interview = Interview.create! valid_attributes
      get :show, {:id => interview.to_param}, valid_session
      expect(assigns(:interview)).to eq(interview)
    end
  end

  describe "GET #new" do
    it "assigns a new interview as @interview" do
      get :new, {}, valid_session
      expect(assigns(:interview)).to be_a_new(Interview)
    end
  end

  describe "GET #edit" do
    it "assigns the requested interview as @interview" do
      interview = Interview.create! valid_attributes
      get :edit, {:id => interview.to_param}, valid_session
      expect(assigns(:interview)).to eq(interview)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Interview" do
        expect {
          post :create, {:interview => valid_attributes}, valid_session
        }.to change(Interview, :count).by(1)
      end

      it "assigns a newly created interview as @interview" do
        post :create, {:interview => valid_attributes}, valid_session
        expect(assigns(:interview)).to be_a(Interview)
        expect(assigns(:interview)).to be_persisted
      end

      it "redirects to the created interview" do
        post :create, {:interview => valid_attributes}, valid_session
        expect(response).to redirect_to(Interview.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved interview as @interview" do
        post :create, {:interview => invalid_attributes}, valid_session
        expect(assigns(:interview)).to be_a_new(Interview)
      end

      it "re-renders the 'new' template" do
        post :create, {:interview => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested interview" do
        interview = Interview.create! valid_attributes
        put :update, {:id => interview.to_param, :interview => new_attributes}, valid_session
        interview.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested interview as @interview" do
        interview = Interview.create! valid_attributes
        put :update, {:id => interview.to_param, :interview => valid_attributes}, valid_session
        expect(assigns(:interview)).to eq(interview)
      end

      it "redirects to the interview" do
        interview = Interview.create! valid_attributes
        put :update, {:id => interview.to_param, :interview => valid_attributes}, valid_session
        expect(response).to redirect_to(interview)
      end
    end

    context "with invalid params" do
      it "assigns the interview as @interview" do
        interview = Interview.create! valid_attributes
        put :update, {:id => interview.to_param, :interview => invalid_attributes}, valid_session
        expect(assigns(:interview)).to eq(interview)
      end

      it "re-renders the 'edit' template" do
        interview = Interview.create! valid_attributes
        put :update, {:id => interview.to_param, :interview => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested interview" do
      interview = Interview.create! valid_attributes
      expect {
        delete :destroy, {:id => interview.to_param}, valid_session
      }.to change(Interview, :count).by(-1)
    end

    it "redirects to the interviews list" do
      interview = Interview.create! valid_attributes
      delete :destroy, {:id => interview.to_param}, valid_session
      expect(response).to redirect_to(interviews_url)
    end
  end

end
