name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      local-linguist-db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Build and run tests
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpg-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake db:setup
          bundle exec rake db:test:prepare
          bundle exec rake spec
